### PR TITLE
Documentation for proc_keyword_init and function to create dirs

### LINKED ISSUE #13: proc_keyword_init fails if output directory not present
`proc_keyword_init(from="2020-01-01")`

> Downloading keyword: Insolvenz
> Downloading daily data
> Downloading data for 2020-01-01 2020-05-21
> Warning in open.connection(path, "wb") :
>   cannot open file '~/trendecon/data-raw/indicator_raw/Insolvenz_d.csv': No such file or directory

Could fix by checking for output directories and creating them if not present.

### LINKED ISSUE #14: proc_keyword_init fails if the from date is in the current year
``` r
pkgload::load_all('~/trendecon')
#> Loading trendecon
#> Loading required package: tidyverse
#> Loading required package: tsbox
proc_keyword_init(from="2020-01-01")
#> Creating data directories if not there.
#> Downloading keyword: Insolvenz
#> Downloading daily data
#> Downloading data for 2020-01-01 2020-05-21
#> Downloading weekly data
#> Downloading data for 2020-01-01 2020-05-21
#> Downloading monthly data
#> Downloading data for 2020-01-01 2020-05-21
#> Downloading data for 2020-02-01 2020-05-21
#> Downloading data for 2020-03-01 2020-05-21
#> Downloading data for 2020-04-01 2020-05-21
#> Downloading data for 2020-05-01 2020-05-21
#> Downloading data for 2020-06-01 2020-05-21
#> Error: Cannot parse the supplied time format.
```

<sup>Created on 2020-05-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### PR DESCRIPTION
**Pull request by uwethuemmel**
Created documentation for `proc_keyword_init`.

While documenting `proc_keyword_init`, I added
- a function in `path_utils.R` to create the data directories in case they don't exist
- throwing an error if more than one keyword is provided
- making sure that the `start_date` in `ts_gtrends_windows` is not after the current date.

Fixes #13 
Fixes #14

### CODE REVIEW

File: R/proc_keyword_init.R [hunk 1]
```diff
@@ -1,6 +1,31 @@
...
+##'     by [trendecon::aggregate_windows].
+#'
+#' @inheritParams ts_gtrends_windows
+#' @param keyword A single keyword to query Google Trends.
+#'
+#' @seealso [ts_gtrends_windows]
 #' @export
+#'
+#' @examples
+#' \dontrun{
```
Comment (christophsax) [inline R/proc_keyword_init.R:22]: Top!
